os: linux
language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
  - "6"
env:
  - CXX=g++-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
install:
  - g++ --version
  - npm --version
  - npm install
script: npm test
