language: node_js
node_js:
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
os:
  - linux
  - osx
sudo: false
install:
  - g++ --version
  - npm --version
  - npm install
  - wc -l src/parser.c
  - wc -c build/Release/*.node
script:
  - npm test
  - bash bin/get-uvm.sh
  - node bin/test-uvm.js
