os: linux
dist: trusty
sudo: required
language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
  - "6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
matrix:
  include:
    - addons:
        apt:
          packages:
            - g++-6
      env:
        - CXX=g++-6
    - addons:
        apt:
          packages:
            - g++-7
      env:
        - CXX=g++-7
install:
  - g++ --version
  - npm --version
  - npm install
script: npm test
